### ISSUE TITLE
Lots of FP from apple imessages

### ISSUE THREAD

**Issue by feanorknd** [coreruleset/fake-bot-plugin#20] opened 2024-03-01 11:16 UTC
Hi there,

apple devices with iMessages using:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0

Will need to disable this plugin and/or modify lua/rule on my own to take care of these requests! (lots of)

Thanks for your work!

**Comment by feanorknd** [comment] 2024-03-01 13:58
Hi @azurit 

this is the user-agent being registered for some requests at nginx logs, and this user-agent is triggering the last version of fakebot plugin configured and installed with modsecurity v4, so rule 9504110 is denying because of the user agent.

If you research a bit, you may see this user agent is commonly used by some apple applications (search for imessages too).

As it contains words reserved for affected robots, lua is performing its checks. ;)
SecRule REQUEST_HEADERS:User-Agent "@pm amazonbot applebot bingbot linkedinbot facebookbot facebookcatalog facebookexternalhit googlebot twitterbot" \

Regards

**Comment by dune73** [comment] 2024-03-01 14:12
It's a stupid situation and the plugin is probably in a very weak situation to make a judgement on a legitimacy of an Apple product claiming to be Facebook. But honestly, the Apple product seems to be giving out wrong information about it's identity and this plugin was designed to detect such anomalies.

The fact that Apple is affected does not make the false claim any better.

Did you open an issue with Apple?

If we get a response from Apple with a technical reason why it's OK to submit this UA in this situation, then we're happy to reconsider. But until then I do not see us changing the plugin.

What you can do it creating a rule exclusion for this situation. Do you need help with that.

**Comment by feanorknd** [comment] 2024-03-01 14:31
Apple sucks, nothing new under the sun.. hehehe

Well, I am just a sysadmin using your excellent plugin, but facing this problem with legit requests... Will just create an exclusion for this user-agent better than disabling.... you are certain ;)

Thanks!

**Comment by azurit** [comment] 2024-03-01 14:44
@feanorknd Thank you, closing this issue!

**Closed by azurit** 2024-03-01 14:44 UTC

**Comment by dune73** [comment] 2024-03-01 16:02
Sounds like a plan. And sorry for the inconvenience.
